### DISCUSSION TITLE
Provide drop-target-dropzone quadrant class

### DISCUSSION THREAD

**Discussion by garyvh2** [mathuo/dockview#450] [Ideas]
Could we add a simple change to allow for customization based on the quadrant we are targeting on drop target?

For instance [here](https://github.com/mathuo/dockview/blob/master/packages/dockview-core/src/dnd/droptarget.ts#L224-L227) we already have the target quadrant.

```javascript
const isLeft = quadrant === 'left';
const isRight = quadrant === 'right';
const isTop = quadrant === 'top';
const isBottom = quadrant === 'bottom';
```

We could do something similar to what we do with these

```javascript
toggleClass(this.overlayElement, 'small-right', isSmallX && isRight);
toggleClass(this.overlayElement, 'small-left', isSmallX && isLeft);
toggleClass(this.overlayElement, 'small-top', isSmallY && isTop);
toggleClass(this.overlayElement, 'small-bottom', isSmallY && isBottom);
```

And change it into something like

```javascript
toggleClass(this.overlayElement, 'small', isSmallX || isSmallY);
toggleClass(this.overlayElement, 'right', isRight);
toggleClass(this.overlayElement, 'left', isLeft);
toggleClass(this.overlayElement, 'top', isTop);
toggleClass(this.overlayElement, 'bottom', isBottom);
```

And scss could change into

```scss
> .drop-target-selection {
    position: relative;
    box-sizing: border-box;
    height: 100%;
    width: 100%;
    background-color: var(--dv-drag-over-background-color);
    transition: top 70ms ease-out, left 70ms ease-out,
        width 70ms ease-out, height 70ms ease-out,
        opacity 0.15s ease-out;
    will-change: transform;
    pointer-events: none;

    &.small {
      &.top {
          border-top: 1px solid var(--dv-drag-over-border-color);
      }

      &.bottom {
          border-bottom: 1px solid var(--dv-drag-over-border-color);
      }

      &.left {
          border-left: 1px solid var(--dv-drag-over-border-color);
      }

      &.right {
          border-right: 1px solid var(--dv-drag-over-border-color);
      }
    }
}
```

That way it would allow us to personalize the `top`, `bottom`, `left` and `right` if needed.
